/** Class Name   : BMECommunitiesSelfRegController 
 *  Description  : This class is An apex page controller that supports self registration of users in BME communities that allow self registration. 
 *  Created By   : Rakesh
 *  Created On   : 22 June 2016
 *
 *  Modification Log:  
 *  --------------------------------------------------------------------------------------------------------------------------------------
 *   Developer                Date                   Modification ID      Description 
 *  --------------------------------------------------------------------------------------------------------------------------------------                                                                                     
 **/

public class Test {

}